name: CI x86_64

on: [push, pull_request, merge_group]
env:
  ARCH: x86_64
  CC: gcc
  CONTAINER_NAMESPACE: ghcr.io/opendataplane/odp-docker-images
  OS: ubuntu_20.04

jobs:
  Build_OS:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        os: ['centos_7', 'rocky_linux_8']
        conf: ['--enable-abi-compat']
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker run -i -v `pwd`:/odp --privileged --shm-size 8g -e CC="${{matrix.cc}}"
               -e CONF="${{matrix.conf}}" $CONTAINER_NAMESPACE/odp-ci-${{matrix.os}}-${ARCH} /odp/scripts/ci/build_${ARCH}.sh
      - if: ${{ failure() }}
        uses: ./.github/actions/build-failure-log
